spring:
  profiles:
    active: local
  ## H2 Configuration
  h2:
    console:
      enabled: true
      path: /linked-erp
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:file:./linked-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    classname: org.h2.Driver
logging:
  level:
    root: DEBUG
